sudo: true

language: cpp
  
os:
  - linux

dist: bionic

compiler: gcc

branches:
  only:
    - master

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -q
  - sudo apt-get install cmake libblas-dev liblapack-dev libopenmpi-dev
  # Install elemental
  - git clone --branch master git://github.com/elemental/Elemental.git ${HOME}/elemental
  - cd ${HOME}/elemental && cmake -H. -Bbuild -DCMAKE_BUILD_TYPE=PureDebug && cmake --build build --target install 
script:
  - cmake -H. -Bbuild
  - cmake --build build
  - ctest --output-on-failure