sudo: false

language: cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - cmake
      - libblas-dev
      - liblapack-dev
      - gfortran-7
      - libopenmpi-dev

dist: bionic

compiler: gcc

branches:
  only:
    - master

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -q
  # Install elemental
  - git clone --branch master git://github.com/elemental/Elemental.git ${HOME}/elemental
  - |
    cd ${HOME}/elemental && 
    cmake -H. -Bbuild -DCMAKE_Fortran_COMPILER=/usr/bin/gfortran-7 -DGFORTRAN_LIB=/usr/lib/gcc/x86_64-linux-gnu/7 && 
    cmake --build build --target install 
script:
  - cmake -H. -Bbuild
  - cmake --build build
  - ctest --output-on-failure