sudo: true

language: cpp
  
os:
  - linux

dist: bionic

compiler: gcc

branches:
  only:
    - master

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -q
  - sudo apt-get install cmake libblas-dev liblapack-dev openmpi
script:
  - cmake -H. -Bbuild
  - cmake --build build
