sudo: false

language: cpp
  
os:
  - linux

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - cmake
  
compiler: gcc

branches:
  only:
    - master
    
script:
  - cmake -H. -Bbuild
  - cmake --build build
